const CERTIFICATION_REASONING_TRAILER_KEY = "Certification-Reasoning"

const CERTIFICATION_SIGNATURE_TRAILER_KEY = "Certification-Signature"

const CERTIFICATION_TRAILER_KEYS: readonly string[] = [
    CERTIFICATION_REASONING_TRAILER_KEY,
    CERTIFICATION_SIGNATURE_TRAILER_KEY
]

export {
    CERTIFICATION_REASONING_TRAILER_KEY,
    CERTIFICATION_SIGNATURE_TRAILER_KEY,
    CERTIFICATION_TRAILER_KEYS
}
