const CERTIFICATION_REASONING_TRAILER_KEY = "Certification-Reasoning"

const CERTIFICATION_SIGNATURE_TRAILER_KEY = "Certification-Signature"

export {
    CERTIFICATION_REASONING_TRAILER_KEY,
    CERTIFICATION_SIGNATURE_TRAILER_KEY
}
